# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0bbbc0aa442c7b7534f39b4a46fd0eb5"
application_url = "https://granted-transmit-corporations-sheets.trycloudflare.com"
embedded = true
name = "subscriptions-block-app"
handle = "subscriptions-block-app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "npm-init-jay.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://granted-transmit-corporations-sheets.trycloudflare.com/auth/callback",
  "https://granted-transmit-corporations-sheets.trycloudflare.com/auth/shopify/callback",
  "https://granted-transmit-corporations-sheets.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
